version: '0.1'
services:
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  FileDatabase:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - mongo_data:/data/db
  AuthDatabase:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=Auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  mongo_data:
  postgres_data:
